<a href="https://colab.research.google.com/github/August65/Sort-numpy-array-/blob/main/sort_numpy_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a=np.array([[1,2,3],[4,1,1],[0,7,10]])
print(a)    

[[ 1  2  3]
 [ 4  1  1]
 [ 0  7 10]]


We will use **np.argsort[:,j-1]** command to sort by column j (because indexing from 0)
so here "0" is sorting by first column, "1" - by second,"2" by third

In [ ]:
b=np.argsort(a[:,0])
print("original array")
print(a)
print("b")
print(b)

original array
[[ 1  2  3]
 [ 4  1  1]
 [ 0  7 10]]
b
[2 0 1]


The output of the command is vector containing indexes of rows to build output - **Sorted array**

In [ ]:
c=a[b]
print(c)

[[ 0  7 10]
 [ 1  2  3]
 [ 4  1  1]]
